# application config for test
# 启动环境变量添加 spring.profiles.active=dev
spring:
  profiles: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#security config
management:
  security:
    enabled: false