# application config
# 公共配置写在这里，需要区分环境的配置写到对应的配置文件中
spring:
  application.name: cloud-admin-server
  profiles:
    active: dev

server.port: 8004

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5

spring.boot.admin.routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream