#application config
spring:
  profiles: dev

#cloud config
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  security:
    enabled: false

#log config
logging:
  file: ./log/eureka-server.log
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: INFO
    com.deloitte.tac.dataengine.npc2017: INFO