#application config
spring:
  profiles: uat

#cloud config
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.173.40.71:8761/eureka/

management:
  security:
    enabled: true

#log config
logging:
  file: /var/log/eureka-server.log
  level:
    root: ERROR
    org.springframework.web: ERROR
    org.hibernate: ERROR
    com.deloitte.tac.dataengine.npc2017: ERROR

